language: node_js

node_js: '10.16.3'

services:
  - docker

addons:
  sonarqube:
    organization: "schnatterer-github"

cache:
    directories:
      - "node_modules"
      - '$HOME/.sonar/cache'
    yarn: true

install:
  - yarn install

script:
  - yarn create-aliases