language: node_js

node_js: '10.16.3'

services:
  - docker

addons:
  sonarqube:
    organization: "schnatterer-github"

cache:
    directories:
      - "node_modules"
      - '$HOME/.sonar/cache'
    yarn: true

install:
  - docker build --no-cache -t docker-aliases .

script:
  # Make sure it creates more than 0 aliases
  - (docker run --rm docker-aliases) 2>&1 | tee >(cat) | grep  'Created ' | grep -v 'Created 0'

