name: Build

on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting with SonarCloud
          fetch-depth: 0

     #  Fails with "Could not find a default branch to fall back on."
     # - uses: sonarsource/sonarcloud-github-action@v1.6
     #   env:
     #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
     #   with:
     #     args: >
     #       -Dsonar.organization=schnatterer-github
     #       -Dsonar.projectKey=info.schnatterer.docker-aliases
  
      - run: docker build --no-cache -t docker-aliases .
      # Make sure it creates more than 0 aliases
      - run: (docker run --rm docker-aliases) 2>&1 | tee >(cat) | grep  'Created ' | grep -v 'Created 0'
